#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use App\Command\QueueMailSendler;

require __DIR__.'/vendor/autoload.php';

$application = new Application();

$application->add(new QueueMailSendler());

$application->run();